database:
  host: validator-dashboard.chexhu4rkdnf.ap-northeast-2.rds.amazonaws.com
  port: 5432
  username: postgres
  password: a4xadmin
  dbname: dashboard

cosmos:
  - juno:
      grpcUrl: juno-grpc.polkachu.com:12690
      denom: ujuno
      validatorOperatorAddr: junovaloper19cdcyqej774srr90qdyxggdf3hcqzq9mknqutc
      validatorAddr: juno19cdcyqej774srr90qdyxggdf3hcqzq9mfwknsp

  - osmosis:
      grpcUrl: osmosis-grpc.polkachu.com:12590
      denom: uosmo
      validatorOperatorAddr: osmovaloper18m4wkxw865cmxu7wv43pk9wgssw022kjyxz6wz
      validatorAddr: osmo18m4wkxw865cmxu7wv43pk9wgssw022kj732ee9
